# Generated by Django 4.0.5 on 2022-06-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companymodel',
            old_name='contact',
            new_name='contact_name',
        ),
        migrations.AddField(
            model_name='companymodel',
            name='phone_number',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
