# Generated by Django 4.0.5 on 2022-06-25 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userapp', '0001_initial'),
        ('serviceapp', '0001_initial'),
        ('companyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerservicemodel',
            name='partnerid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partnerservicemodel',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceapp.servicemodel'),
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='partnerid',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='quote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.quotemodel'),
        ),
        migrations.AddField(
            model_name='companymodel',
            name='cities',
            field=models.ManyToManyField(to='serviceapp.servicecitiesmodel'),
        ),
        migrations.AddField(
            model_name='companymodel',
            name='services',
            field=models.ManyToManyField(to='serviceapp.servicemodel'),
        ),
        migrations.AddField(
            model_name='acceptedquotemodel',
            name='partnerid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='companyapp.partnerservicemodel'),
        ),
        migrations.AddField(
            model_name='acceptedquotemodel',
            name='quote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.quotemodel'),
        ),
    ]
