# Generated by Django 4.0.5 on 2022-06-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyapp', '0002_rename_contact_companymodel_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymodel',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
