# Generated by Django 4.0.5 on 2022-06-24 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companyapp', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerservicemodel',
            name='partnerid',
        ),
    ]
