# Generated by Django 4.0.5 on 2022-06-21 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('serviceapp', '0005_servicemodel_photo'),
        ('companyapp', '0004_companymodel_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerServiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('quote', models.BooleanField(default=False)),
                ('booking', models.BooleanField(default=False)),
                ('partnerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceapp.servicemodel')),
            ],
        ),
    ]
