# Generated by Django 4.0.5 on 2022-06-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyapp', '0005_partnerservicemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerservicemodel',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='partnerservicemodel',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
