# Generated by Django 4.0.5 on 2022-06-22 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companyapp', '0007_notificationmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationmodel',
            old_name='partner_id',
            new_name='partnerid',
        ),
    ]
