# Generated by Django 4.0.5 on 2022-06-22 08:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companyapp', '0008_rename_partner_id_notificationmodel_partnerid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationmodel',
            name='partnerid',
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='partnerid',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
