# Generated by Django 4.0.5 on 2022-06-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotemodel',
            name='unique_code',
            field=models.CharField(default='20220625149820c6f4-bec5-4593-ab07-79f2078650c7', editable=False, max_length=100),
        ),
    ]
