# Generated by Django 4.0.5 on 2022-07-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotemodel',
            name='unique_code',
            field=models.CharField(default='2022070214eae9c114-c7f5-46c3-9043-352b555d75c1', editable=False, max_length=100),
        ),
    ]
