# Generated by Django 4.0.5 on 2022-06-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotemodel',
            name='unique_code',
            field=models.CharField(default='2022062812896d6bf8-1841-4d5c-8d3e-ec3f3c6526a3', editable=False, max_length=100),
        ),
    ]
