# Generated by Django 4.0.5 on 2022-07-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_alter_quotemodel_unique_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotemodel',
            name='unique_code',
            field=models.CharField(default='202207021473158b56-d25c-48c8-82fc-c3aad867f93b', max_length=100),
        ),
    ]
