# Generated by Django 4.0.5 on 2022-06-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_alter_quotemodel_unique_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotemodel',
            name='unique_code',
            field=models.CharField(default='20220628125529a6ff-7eac-4e5d-93a4-9ac510a554f1', editable=False, max_length=100),
        ),
    ]
