# Generated by Django 4.0.5 on 2022-06-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_alter_quotemodel_unique_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotemodel',
            name='unique_code',
            field=models.CharField(default='20220628128eca4503-97dc-47d6-94d3-20d5a29d0587', editable=False, max_length=100),
        ),
    ]
