# Generated by Django 4.0.5 on 2022-06-21 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_quotemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotemodel',
            old_name='locattion',
            new_name='service_location',
        ),
    ]
