# Generated by Django 4.0.5 on 2022-07-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_alter_quotemodel_unique_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotemodel',
            name='unique_code',
            field=models.CharField(default='202207021427e62e81-ded1-4eb7-ad54-4a267df7b9a4', editable=False, max_length=100),
        ),
    ]
