# Generated by Django 4.0.5 on 2022-06-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_alter_quotemodel_unique_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotemodel',
            name='unique_code',
            field=models.CharField(default='2022062812d7eee7de-6676-4685-b8d7-84bd0a3eaf8c', editable=False, max_length=100),
        ),
    ]
