# Generated by Django 4.0.5 on 2022-06-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_rename_locattion_quotemodel_service_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='is_partner',
            field=models.BooleanField(default=False),
        ),
    ]
