# Generated by Django 4.0.5 on 2022-07-02 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_alter_quotemodel_unique_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotemodel',
            name='unique_code',
        ),
    ]
