# Generated by Django 4.0.5 on 2022-06-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_usermodel_is_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotemodel',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
