# Generated by Django 4.0.5 on 2022-06-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_alter_quotemodel_unique_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotemodel',
            name='unique_code',
            field=models.CharField(default='202206281514883004-7b60-4f89-9a40-8041d7669d7c', editable=False, max_length=100),
        ),
    ]
