# Generated by Django 4.0.5 on 2022-07-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_remove_quotemodel_unique_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotemodel',
            name='unique_code',
            field=models.CharField(default='20220702147732a4dc-1737-4f20-b0c0-d8e1b46a1a3a', editable=False, max_length=100),
        ),
    ]
