# Generated by Django 4.0.5 on 2022-07-04 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_alter_quotemodel_unique_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotemodel',
            name='unique_code',
            field=models.CharField(default='2022070409644d3c87-5a53-4ca0-b242-d1ea0cc9fb1f', editable=False, max_length=100),
        ),
    ]
