# Generated by Django 4.0.5 on 2022-07-04 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_alter_quotemodel_unique_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotemodel',
            name='unique_code',
            field=models.CharField(default='2022070409ae2886f6-b3ae-478a-882d-f3a6294a82a7', editable=False, max_length=100),
        ),
    ]
