# Generated by Django 4.0.5 on 2022-07-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_alter_quotemodel_unique_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotemodel',
            name='unique_code',
            field=models.CharField(default='202207041413b25255-d0bd-4518-a02a-6c81c6840fce', editable=False, max_length=100),
        ),
    ]
