# Generated by Django 4.0.5 on 2022-07-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_alter_quotemodel_unique_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotemodel',
            name='unique_code',
            field=models.CharField(default='2022070417de303b79-3498-4a49-97ec-049bfdc3b6d2', editable=False, max_length=100),
        ),
    ]
