# Generated by Django 4.0.5 on 2022-07-04 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0002_servicelinkmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicelinkmodel',
            name='services',
        ),
        migrations.AddField(
            model_name='servicelinkmodel',
            name='services',
            field=models.ManyToManyField(to='serviceapp.servicemodel'),
        ),
    ]
