# Generated by Django 4.0.5 on 2022-07-04 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0003_remove_servicelinkmodel_services_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServicelinkModel',
        ),
    ]
