# Generated by Django 4.0.5 on 2022-06-21 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0003_rename_services_servicetypemodel_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecitiesmodel',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='servicecitiesmodel',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
