# Generated by Django 4.0.5 on 2022-07-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0004_delete_servicelinkmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemodel',
            name='popular',
            field=models.BooleanField(default=False),
        ),
    ]
