# Generated by Django 4.0.5 on 2022-06-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0005_servicemodel_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecitiesmodel',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='servicetypemodel',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
